#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WIDTH 960
#define HEIGHT 540

#define SPAWNING_TIME_MOSQUITO 10.0f
#define SPAWNING_TIME_SERPIENTE 7.0f
#define SPAWNING_TIME_ARBUSTO 1.5f
#define SPAWNING_TIME_ROCA 1.5f


#endif
